
--CONSULTAS

--#1 PRODUCTO VENDIDOS DE LA SEMANA
CREATE PROC SP_PRODUCTOSEMANAL (@fechaInicial DATE,@fechaFinal DATE)
AS
BEGIN
	SELECT T0.NOMPRODUC,T1.CANTIDAD,T2.CODVENT,T2.FECHA_EMI,FECHA_ENTREGA
	FROM PRODUCTO T0 INNER JOIN DETALLEVENTA T1 ON T0.CODPRODUCTO = T1.CODPRODUCTO INNER JOIN DOCUMENTOVENTA T2 ON T1.CODVENT =T2.CODVENT
	WHERE FECHA_EMI >=@fechaInicial AND FECHA_EMI <= @fechaFinal
END
GO
EXEC SP_PRODUCTOSEMANAL '2024-08-01','2024-08-05'

--#2 VENTAS DE UN EMPLEADO EN UN TIEMPO ESTIMADO
CREATE PROC SP_VENTASEMPLEADO (@Vendedor CHAR(5),@fecha DATE)
AS
BEGIN
	SELECT	T0.NOMBRE+' '+T0.APELLIDO [Nombre Completo],T2.CODVENT [NRO VENTA],T2.FECHA_EMI,T4.NOMPRODUC [PRODUCTO],T3.CANTIDAD,T1.NOMBRE [DISTRITO]
	FROM EMPLEADO T0 INNER JOIN DISTRITO T1 ON T0.CODDISTRITO = T1.CODDISTRITO INNER JOIN DOCUMENTOVENTA T2 ON T0.CODEMPLE = T2.CODEMPLE 
					 INNER JOIN DETALLEVENTA T3 ON T2.CODVENT = T3.CODVENT INNER JOIN PRODUCTO T4 ON T3.CODPRODUCTO = T4.CODPRODUCTO
	WHERE T0.CODEMPLE = @Vendedor AND T2.FECHA_EMI >=@fecha
END 
GO
EXEC SP_VENTASEMPLEADO 'E001','2024-01-01'


--#3 FILTRO DE EMPLEADOS DE UN CARGO Y DISTRITO ESPECIFICO 
CREATE PROC SP_EMPLEADO_CARGO_DISTRITO(@cargo CHAR(6),@distrito CHAR(6))
AS
BEGIN 
	SELECT T0.NOMBRE+' '+T0.APELLIDO [NOMBRE],T0.TELEFONO,T1.NOMBRE [CARGO],T2.NOMBRE [DISTRITO]
	FROM EMPLEADO T0 INNER JOIN CARGO T1 ON T0.CODCARGO = T1.CODCARGO INNER JOIN DISTRITO T2 ON T0.CODDISTRITO = T2.CODDISTRITO
	WHERE T1.CODCARGO =@cargo AND T2.CODDISTRITO = @distrito
END
GO
EXEC SP_EMPLEADO_CARGO_DISTRITO 'C010','D010'


--#4 REPORTE DE MOVIMIENTO DE SALIDO DE UN PRODUCTO ESPECIFICO
CREATE PROC SP_MOVIMIENTO_PRODUCTO(@Producto CHAR(6),@Movimiento CHAR(7))
AS
	BEGIN
		SELECT T0.NOMPRODUC,T0.CODPRODUCTO,T1.TIPOMOVIMIENTO,T1.CANTIDAD,T2.FECHAMOVIMIENTO
		FROM PRODUCTO T0 INNER JOIN DETALLEMOVIMIENTO T1 ON T0.CODPRODUCTO = T1.CODPRODUCTO 
						INNER JOIN MOVI_INVENTARIO T2 ON T1.COD_MOVI_INVEN = T2.COD_MOVI_INVEN
		WHERE T0.CODPRODUCTO = @Producto AND T1.TIPOMOVIMIENTO = @Movimiento
	END
GO
EXEC SP_MOVIMIENTO_PRODUCTO 'PROD01','SALIDA'


--#5 CANTIDAD DE MATERIA PRIMA PARA PRODUCIR UN PRODUCTO
CREATE PROC MATERIA_PRODUCTO (@Materia CHAR(5),@Producto CHAR(6))
AS
	BEGIN
		SELECT T0.NOMBRE [MATERIA],T0.DESCRIPCION,T1.CANTIDAD_MATERIA,T2.NOMPRODUC,T2.PRECIO_UNI
		FROM MATERIA_PRIMA T0 INNER JOIN DETALLEP_M_P T1 ON T0.CODMATERIA = T1.CODMATERIA 
						      INNER JOIN PRODUCTO T2 ON T1.CODPRODUCTO = T2.CODPRODUCTO
		WHERE T0.CODMATERIA = @Materia AND T2.CODPRODUCTO = @Producto
	END
GO
EXEC MATERIA_PRODUCTO 'MAT1','PROD01'


--#6 REGISTRO DE UN TIPO DE RECIBO
CREATE PROC SP_TIPORECIBO_SEMANA(@TipoDocument CHAR(13),@Fecha DATE)
AS
	BEGIN
		SELECT T1.NOMBRE [TIPO DOCUMENTO],T0.FECHA_EMI,T3.NOMPRODUC [PRODUCTO],T2.CANTIDAD
		FROM DOCUMENTOVENTA T0 INNER JOIN TIPO_DOCUMENTO T1 ON T0.COD_TIPO_DOCUMENTO = T1.COD_TIPO_DOCUMENTO 
								INNER JOIN  DETALLEVENTA T2 ON T0.CODVENT = T2.CODVENT
								INNER JOIN PRODUCTO T3 ON T2.CODPRODUCTO = T3.CODPRODUCTO
		WHERE T1.COD_TIPO_DOCUMENTO = @TipoDocument AND T0.FECHA_EMI >=@Fecha
	END
GO
EXEC SP_TIPORECIBO_SEMANA 'TD001','2024-05-01'


--#7 CONSULTA DE SUMA DE IMPORTES DE UN PRODUCtO EN DETERMINADA FECHA
CREATE PROC SP_IMPORTE_PRODUCTO (@fechaInicial DATE,@fechaFinal DATE)
AS
	BEGIN
		SELECT T0.NOMPRODUC,SUM(T1.IMPORTE)
		FROM PRODUCTO T0 INNER JOIN DETALLEVENTA T1 ON T0.CODPRODUCTO = T1.CODPRODUCTO 
						 INNER JOIN DOCUMENTOVENTA T2 ON T1.CODVENT = T2.CODVENT
		WHERE T2.FECHA_EMI BETWEEN @fechaInicial AND @fechaFinal
		GROUP BY T0.NOMPRODUC
	END
GO
EXEC SP_IMPORTE_PRODUCTO '2024-01-01','2024-08-01'

--#8 CONSULTA DE VENTAS DE UN ACABADO EN ESPECIFICO
CREATE PROC ACABADO_PRODUCTO_VENTA(@acabado CHAR(6),@fechaInicial DATE,@fechaFinal DATE)
AS
	BEGIN
		SELECT T1.NOMBRE [ACABADO],T3.CODVENT [NRO VENTA],T0.NOMPRODUC [PRODUCTO],T2.CANTIDAD
		FROM PRODUCTO T0 INNER JOIN TIPOACABADO T1 ON T0.CODACABADO = T1.CODACABADO 
						 INNER JOIN DETALLEVENTA T2 ON T0.CODPRODUCTO = T2.CODPRODUCTO
						 INNER JOIN DOCUMENTOVENTA T3 ON T2.CODVENT = T3.CODVENT
		WHERE (T1.CODACABADO = @acabado) AND (T3.FECHA_EMI BETWEEN @fechaInicial AND @fechaFinal)
	END
GO
EXEC ACABADO_PRODUCTO_VENTA 'ACA01','2024-08-01','2024-08-30'


--#9 CONSULTA DE CANTIDAD DE VENTAS DE CLIENTES
CREATE PROC SP_SUMA_VENTAS_CLIENTE(@fechaInicial DATE,@fechaFinal DATE)
AS
	BEGIN
	SELECT T1.NOMBRE+' '+T1.APELLIDO [NOMBRES],T2.NOMBRE [DISTRITO], COUNT(*)[CANTIDAD VENTAS]
	FROM DOCUMENTOVENTA T0 INNER JOIN  CLIENTE T1  ON T0.IDCLIENTE = T1.IDCLIENTE
							INNER JOIN DISTRITO T2 ON T1.CODDISTRITO = T2.CODDISTRITO 
	WHERE T0.FECHA_EMI >= @fechaInicial AND T0.FECHA_EMI <= @fechaFinal
	GROUP BY T1.NOMBRE,T1.APELLIDO,T2.NOMBRE
	END
GO
EXEC SP_SUMA_VENTAS_CLIENTE '2024-08-01','2024-08-30'


--#10 VENTAS OPTIMA DE UN EMPLEADO
CREATE PROC VENTAS_OPTIMAS (@Monto MONEY,@FechaiNI DATE,@FechaFIN DATE)
AS	
	BEGIN
		SELECT T1.NOMBRE+' '+T1.APELLIDO [EMPLEADO],SUM(T2.IMPORTE)[SUMA IMPORTE]
		FROM DOCUMENTOVENTA T0 INNER JOIN EMPLEADO T1 ON T0.CODEMPLE = T1.CODEMPLE INNER JOIN DETALLEVENTA T2 ON T0.CODVENT = T2.CODVENT
		WHERE  T0.FECHA_EMI BETWEEN @FechaiNI AND @FechaFIN
		GROUP BY T1.NOMBRE,T1.APELLIDO
		HAVING SUM(T2.IMPORTE) >= @Monto
	END
GO
EXEC VENTAS_OPTIMAS 1200.00,'2024-01-01','2024-08-31'


--VISTAS

--VISTA 1 INFO MATERIA PRIMA 
CREATE VIEW V_MATERIA
AS
SELECT T0.NOMBRE,T0.DESCRIPCION,T1.NOMBRE [PROVEEDOR],T2.NOMBRE [UNIDAD MEDIDA]
FROM MATERIA_PRIMA T0 INNER JOIN PROVEEDORES T1 ON T0.CODPROVEEDOR = T1.CODPROVEEDOR INNER JOIN UNI_MEDIDA T2 ON T0.COD_UNI_MEDIDA = T2.COD_UNI_MEDIDA
GO
SELECT * FROM V_MATERIA

--VISTA 2 INFO  DE DOCUMENTO DE VENTA
CREATE VIEW V_VENTAS_DETALLADAS
AS
	SELECT T0.CODVENT,T2.NOMBRE+' '+T2.APELLIDO [EMPLEADO],T2.EMAIL,T1.NOMBRE+' '+T1.APELLIDO [CLIENTE],T1.TELEFONO
	FROM DOCUMENTOVENTA T0 INNER JOIN CLIENTE T1 ON T0.IDCLIENTE = T1.IDCLIENTE INNER JOIN EMPLEADO T2 ON T0.CODEMPLE = T2.CODEMPLE
GO
SELECT * FROM V_VENTAS_DETALLADAS

--VISTA 3 LISTA DE LOS TAMAÑOS DE PRODUCTO QUE TUVIERON MOVIMIENTO
CREATE VIEW V_MOVIMIENTO_TAMANHO
AS
	SELECT T1.NOMBRE [TAMAÑO],T2.TIPOMOVIMIENTO [MOVIMIENTO],T3.FECHAMOVIMIENTO,T0.NOMPRODUC [PRODUCTO]
	FROM PRODUCTO T0 INNER JOIN TIPOTAMANHO T1 ON T0.CODTAMANHO = T1.CODTAMANHO 
					INNER JOIN DETALLEMOVIMIENTO T2 ON T0.CODPRODUCTO = T2.CODPRODUCTO
					INNER JOIN MOVI_INVENTARIO T3 ON T2.COD_MOVI_INVEN = T3.COD_MOVI_INVEN
GO
SELECT * FROM V_MOVIMIENTO_TAMANHO

--VISTA 4 DESCRIPCION PRODUCTO
CREATE VIEW V_PRODUCTO_CARACTERISTICAS
AS
	SELECT T0.NOMPRODUC [PRODUCTO],T1.NOMBRE [ACABADO],T2.NOMBRE [GRAMAJE],T3.NOMBRE [TAMAÑO]
	FROM PRODUCTO T0 INNER JOIN TIPOACABADO T1 ON T0.CODACABADO = T1.CODACABADO
					 INNER JOIN TIPOGRAMAJE T2 ON T0.CODGRAMAJE = T2.CODGRAMAJE
					 INNER JOIN TIPOTAMANHO T3 ON T0.CODTAMANHO = T3.CODTAMANHO
GO
SELECT * FROM V_PRODUCTO_CARACTERISTICAS

--VISTA 5 DESCRIPCION EMPLEADO
CREATE VIEW V_EMPLEADO_INFO
AS
	SELECT T0.NOMBRE+' '+T0.APELLIDO [NOMBRE],T0.DNI,T0.DIRECCION,T0.TELEFONO,T0.FECHA_INGRESO,T0.SALARIO,
					T1.NOMBRE [CARGO],T2.NOMBRE [AREA],T3.NOMBRE [DISTRITO]
	FROM EMPLEADO T0 INNER JOIN CARGO T1 ON T0.CODCARGO = T1.CODCARGO
					 INNER JOIN AREA T2 ON T0.CODAREA = T2.CODAREA
					 INNER JOIN DISTRITO T3 ON T0.CODDISTRITO = T3.CODDISTRITO
GO
SELECT * FROM V_EMPLEADO_INFO